version: '1.0'
name: ejercicio_1_1
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    - CLI_NOMBRE=nombre-1
    - CLI_APELLIDO=apellido-1
    - CLI_DOCUMENTO=40000001
    - CLI_NACIMIENTO=2000-01-02
    - CLI_NUMERO=10001
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    depends_on:
    - server
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=2
    - CLI_LOG_LEVEL=DEBUG
    - CLI_NOMBRE=nombre-2
    - CLI_APELLIDO=apellido-2
    - CLI_DOCUMENTO=40000002
    - CLI_NACIMIENTO=2000-01-03
    - CLI_NUMERO=10002
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    depends_on:
    - server
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=3
    - CLI_LOG_LEVEL=DEBUG
    - CLI_NOMBRE=nombre-3
    - CLI_APELLIDO=apellido-3
    - CLI_DOCUMENTO=40000003
    - CLI_NACIMIENTO=2000-01-04
    - CLI_NUMERO=10003
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    depends_on:
    - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
